# Wsparcie GroDev / Dominik Groński
# Jeśli któreś z moich publicznych repo się przydało - dzięki!
# Kontakt/oferty komercyjne: dominik@grodev.pl · https://grodev.pl

github: [GronskiDeveloper]
custom: ['https://grodev.pl/wsparcie', 'https://grodev.pl/kontakt']
